# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Page 8
Post date = March 30, 2026
# You can delete any of the lines below if you don't want to use them.
Alt text = The purple cat Kaia is proud as they head deeper into the store througha  hole int he wall perfectly sized for an animal their size. Inside the room, we can see Kaia has been preparing something by using several natural ingredients like flowers and spices and an assortment of potions. Kaia is putting drops of liquid in a beaker as they were protective glasses, later they are swirling the contents of the beaker while he is smugly looking at it, then Kaia is looking at the red flower in the room bloom with pink and blues within, a tear in their eye as it happens. Then Kaia is shocked as they are reading the book of "Side effects of the holly & willow.
Storyline = Chapter 1
Characters = Kaia
Tags =