# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Page 15
Post date = August 14, 2026
# You can delete any of the lines below if you don't want to use them.
Alt text = A large town can be sween with several inhabitants, some looks scholarly while others look like they are rich having chained demons in their grasp doing their bidding. Several Cerulean Knights are posted around the streets keeping guard or arresting others. We are focused mainly on a large tea shop that loks exclusive. Two tea cups of a frutal beverage can be seen as a human hand belonging to Umbra reaches for one followed by Liz's tail reaching for the other. Liz not wearing her helmet anymore looks at Umbra annoyed as she holds her tea while Umbra is uncaring in their demeanor.
Storyline = Chapter 1
Characters = Umbra, Liz
Tags = Cameo