# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Page 10
Post date = April 10, 2026
# You can delete any of the lines below if you don't want to use them.
Alt text = Kaia the purple cat is trying to explain to the ceruean knight but is interrupted rudely making Kaia have true fear ni their eyes. As the cerulean knight talks, Kaia internally is shocked about something they mentioned. Kaia is then very anxious as they are trembling on the spot. Outside of the WIzard's pets shop, Sally is approaching the store happily.
Storyline = Chapter 1
Characters = Sally, Kaia, Cerulean Captain
Tags = 