# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Page 12
Post date = May 14, 2026
# You can delete any of the lines below if you don't want to use them.
Alt text = The Cerulean captain is kneeling over the desk of the store messing with a wand in their hands, suddenly they feel someone arriving. The yellow dog enters the store excited to be there as the panels once again become vibrant with color. Standing at the desk is Kaia the cat back to normal as if nothing had happened.
Storyline = Chapter 1
Characters = Sally, Cerulean Captain
Tags = 