# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Page 17
Post date = October 2, 2026
# You can delete any of the lines below if you don't want to use them.
Alt text = The yellow dog is freaking out and we are then in a black and white scene of the dog looking around her afraid of three large humanoid chadows, she has large glasses on the bridge of her nose. She then snaps back awake and looks a bit flustered down at her neck.
Storyline = Chapter 1
Characters = Sally
Tags = 