# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Page 4
Post date = October 13, 2025
# You can delete any of the lines below if you don't want to use them.
Alt text = The yellow dog is fully awake talking with the green anthro dragon with red hair, a shiny yellow orb is in focus. The dog extends her reach towards the ball and her ears begin to glow a golden yellow.
Storyline = Chapter 1
Characters = Sally
Tags = Cameo, Dice Roll