# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Page 9
Post date = April 7, 2026
# You can delete any of the lines below if you don't want to use them.
Alt text = Kaia is happily laid on their back as they are relaxed surrounded of trinkets and books. A bell rings further away and Kaia initially looks happy but is immediately in shock as the color of the panel drains away into a grim light blue. Kaia peeking from the counter of the store looks up at a huge knight, blue colors surrounding the area, a luminicent white coming through the hole in the knight's helmet. The knight is bulky and seems to be brandishing a weapon.
Storyline = Chapter 1
Characters = Kaia, Cerulean Captain
Tags = Cameo