# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Page 11
Post date = May 5, 2026
# You can delete any of the lines below if you don't want to use them.
Alt text = The red haired human mage is hiding behind a tree dodging several Cerulean knights and a soul warden that are scouring the area where debris has fallen. Umbra finds a mysterious plate that seems to belong to some school. Kaia looks as he has been spotted by a cerulean knight that appears to be a snake donning prosthetic arms and a large spear. Umbra pretends to be in danger which annoys the snake knight.
Storyline = Chapter 1
Characters = Kaia, Liz
Tags = 