# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Page 14
Post date = June 6, 2026
# You can delete any of the lines below if you don't want to use them.
Alt text = The Cerulean captain disguised as Kaia is pretending everything is normal, the yellow dog begins to explore the shop some more when the captain spots her and yells at her, the dog looks annoyed at the disguised cat vendor while holding a few stone pebbles on her paw. Its revealed that there is a statue in the shape of a smiling Kaia who has now been petrified.
Storyline = Chapter 1
Characters = Sally, Kaia, Cerulean Captain
Tags = 