# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Page 3
Post date = October 7, 2025
# You can delete any of the lines below if you don't want to use them.
Alt text = First person perspective of the green dragon with red hair looking down at the viewer, worried and puzzled followed by a closeup of the yellow dog waking up confused
Characters = Sally, GigabyteDragon
Tags = Cameo