# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Page 13
Post date = May 27, 2026
# You can delete any of the lines below if you don't want to use them.
Alt text = The purple cat is split in two different panels, a happy colorful and vibrant one followed by a gloomy blue one with disdain from the cat, clearly showing that the cat currently is the cerulean captain in disguise. The yellow dog is impressed upon seeing a scroll in display, she asks a question about it to the disguised cat to which Sally immediately becomes confused, later posing smugly as the disguised cat seems to be stunned.
Storyline = Chapter 1
Characters = Sally, Cerulean Captain
Tags =