# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Page 16
Post date = September 21, 2026
# You can delete any of the lines below if you don't want to use them.
Alt text = The yellow dog is dismissing the cat vendor and prepare to leave. The cerulean captain as Kaia stops her while forcing a smile showing their teeth awkwardly, internally they are analyzing the situation. The dog's train of thought is completely halted as they are shocked at what was asked at her, the colors of the panel drain into a wait even on the cat vendor all but the dog herself.
Storyline = Chapter 1
Characters = Sally, Kaia, Cerulean Captain
Tags = 