# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Page 5
Post date = November 8, 2025
# You can delete any of the lines below if you don't want to use them.
Alt text = The yellow orb levitates towards the dog and lands on her paws, the green anthro dragon with red hair is shocked at the events ocurring to the point of being afraid. The dog seems to be calm, requesting something from the dragon.
Storyline = Chapter 1
Characters = Sally
Tags = Cameo