# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Page 6
Post date = November 22, 2025
# You can delete any of the lines below if you don't want to use them.
Alt text = A small shack in the middle of the woods surrounded on the base by what looks like yellow plates growing around it, it seems to be a store called "The Wizard's Pets." Inside we see a huge assortment of relics, ingredients and potion bottles and even a cash register with a mage doning a large hat sleeping on the job alongside a purple cat laid on the desk itself. There is a solar themed clock on the wall, time ticking. The Mage is awoken showing a bluish purple eye strain around their sclera. The mage gets up abruptly which wakes up the purple cat who seems annoyed at the mage.
Storyline = Chapter 1
Characters = Kaia, Umbra
Tags = 