# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Chapter 1 Page 1
Post date = September 26, 2025
# You can delete any of the lines below if you don't want to use them.
Alt text = A yellow dog falling from the sky as debris blazing on fire falls alongside the dog. It's a daytime sky with a town below and a huge medieval city on a cliff surrounded by a magical blue dome.
Storyline = Chapter 1
Characters = Sally
Tags = Tag 1, Tag 2, Tag 3