# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Page 7
Post date = December 17, 2025
# You can delete any of the lines below if you don't want to use them.
Alt text = The human mage with red hair is talking showing a closed sign as they are about to close the door, the door of the Wizard's Pets shop is slammed shut with force. The purple cat yawns as they stretch their body to wake up, polished shiny blue nails showing. The purple cat shows a name tag on their collar with the name "Kaia" as they smile and disregard the mage's behaviour who he calls "Umbra". Outside, Umbra is heading out into the forest with a staff donning a red gem at the top, behind a tree a shadowy figure with a sinister blue glow on what can be seen as the helmet of a knight stares at the mage who leaves.
Storyline = Chapter 1
Characters = Kaia, Umbra, Cerulean Captain
Tags = 