# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Page 2
Post date = October 3, 2025
# You can delete any of the lines below if you don't want to use them.
Alt text = The yellow dog falling from the sky crashes loudly on the ground making a loud impact. THe ground is marked with impact craters from the dog herself ina  straight line towards us and the large falling debris chunks still falling from above. There isa  green anthropomorphic dragon with red hair approaching the scene.
Storyline = Chapter 1
Characters = Sally, GigabyteDragon
Tags = Cameo